export const API_TOKEN_LOADED = 'API_TOKEN_LOADED';
export const REQUEST_API_TOKEN = 'REQUEST_API_TOKEN';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REQUEST_APIM_TOKEN = 'REQUEST_APIM_TOKEN';
export const APIM_TOKEN_LOADED = 'APIM_TOKEN_LOADED';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_BILLS = 'GET_BILLS';
export const SET_BILLS = 'SET_BILLS';
export const RESET_BILLS = 'RESET_BILLS';
export const SET_SELECTED_BILL = 'SET_SELECTED_BILL';
export const REQUEST_BILL_DETAILS = 'REQUEST_BILL_DETAILS';
export const RECEIVE_BILL_DETAILS = 'RECEIVE_BILL_DETAILS';
export const REQUEST_UPDATE_BILL_DETAILS = 'REQUEST_UPDATE_BILL_DETAILS';

export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const RESET_CUSTOMERS = 'RESET_CUSTOMERS';
export const ISTOKEN_REQUEST = 'ISTOKEN_REQUEST';
export const ISTOKEN_SUCCESS = 'ISTOKEN_SUCCESS';

export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const CUSTOMER_DONE_LOADING = 'CUSTOMER_DONE_LOADING';
export const LOAD_USER = 'LOAD_USER';
export const USER_LOADED = 'USER_LOADED';
